name: Generate smart tag for Docker images
description: Generate Docker tag for each branches or tags
author: Kosei Kitahara
outputs:
  tag:
    description: Smart tag
runs:
  using: 'node12'
  main: 'dist/index.js'
